services:

  vox_db:
    image: mysql:9.6.0
    container_name: vox_db
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vox
      MYSQL_USER: vox
      MYSQL_PASSWORD: vox
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uvox", "-pvox"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - vox_network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      vox_db:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: vox_db
      DB_PORT: 3306
      DB_DATABASE: vox
      DB_USERNAME: vox
      DB_PASSWORD: vox
    command: sh -c "./start.sh"
    networks:
      - vox_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: sh -c "CI=true pnpm install && pnpm run dev --host --port 3000"
    networks:
      - vox_network

volumes:
  mysql_data:

networks:
  vox_network: